name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and analyze
        run: mvn verify sonar:sonar \
          -Dsonar.projectKey=Wafa458_CICD-Assignment-2 \
          -Dsonar.organization=wafa458 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}